use std::{fs, path::PathBuf};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn strict_interface_is_the_sole_schema_authority() {
    let root = root();
    let source =
        fs::read_to_string(root.join("ethos/interface.ethos")).expect("strict Interface exists");
    let generated =
        fs::read_to_string(root.join("src/schema/lib/generated.rs")).expect("projection exists");
    let manifest = fs::read_to_string(root.join("src/bootstrap_manifest.rs"))
        .expect("authority manifest exists");

    assert!(source.starts_with("Interface.{1 0 0}\n[]\n{"));
    assert!(source.contains("CriomeRequest.["));
    assert!(source.contains("CriomeReply.["));
    assert!(
        !root.join("schema/lib.schema").exists(),
        "legacy schema authority must be absent"
    );
    assert!(generated.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface"
    ));
    assert!(!generated.contains("CriomeRequest"));
    assert!(!generated.contains("CriomeReply"));
    assert!(manifest.matches("DeclarationSeat::new").count() > 300);
}
