// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VdZ4(std::string::String);
impl z2VdZ4 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VUiL {
    pub field_0: z2VZMH,
    pub field_1: z2VL5X,
    pub field_2: z2VPdA,
}
pub struct z2VNo7 {
    pub field_0: Option<z2Vb3i>,
    pub field_1: Option<z2VReV>,
}
pub struct z2VUfX(u64);
impl z2VUfX {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VZZu {z2VTm7 ( z2VXA2 ,) , z2VPcz , z2VdWC , z2VMGJ , z2VUM8 ( z2VM1c ,) ,} 
pub struct z2VMiY(std::string::String);
impl z2VMiY {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VcHz {
    pub field_0: z2VfEn,
    pub field_1: z2VQHy,
    pub field_2: z2VMbZ,
}
pub struct z2Vbch {
    pub field_0: z2VZMH,
    pub field_1: z2VL5X,
    pub field_2: z2VVvg,
}
pub struct z2VP1D {
    pub field_0: z2VbTN,
    pub field_1: z2VUfX,
    pub field_2: Vec<z2VL5X>,
}
pub struct z2VSJ5 {
    pub field_0: z2VWaA,
    pub field_1: z2VPfK,
}
pub struct z2VTRq {
    pub field_0: z2Vf4i,
    pub field_1: z2VVvg,
}
pub struct z2VVC4 {
    pub field_0: z2VL5X,
    pub field_1: z2VRpF,
}
pub struct z2VQsx {
    pub field_0: z2VbxF,
    pub field_1: z2VbxF,
    pub field_2: z2VL5X,
}
pub struct z2VYrq {
    pub field_0: z2VL5X,
    pub field_1: z2VVvg,
}
pub struct z2VPDB {
    pub field_0: z2VduC,
    pub field_1: z2VLn9,
}
pub struct z2VVmW(Vec<z2VLMo>);
impl z2VVmW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VLMo>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VLMo> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VLMo> {
        self.0
    }
}
pub struct z2Vf4i {
    pub field_0: z2VP1D,
    pub field_1: Vec<z2VYrq>,
}
pub struct z2VRPv {
    pub field_0: z2VaDY,
    pub field_1: z2Vevu,
    pub field_2: z2VZZu,
    pub field_3: z2Vf4i,
}
pub enum z2VPMJ {z2VRwy , z2VWCR , z2VWYS , z2VN1i , z2Vdxz , z2VYVC ,} 
pub struct z2VVvg {
    pub field_0: z2VPCX,
    pub field_1: z2VdZ4,
    pub field_2: z2VZjL,
}
pub enum z2VYM1 {z2VUdX , z2VWW6 ,} 
pub struct z2VVNR {
    pub field_0: z2VdZJ,
    pub field_1: z2VL5X,
}
pub struct z2VR27 {
    pub field_0: z2Vevu,
    pub field_1: z2VbzK,
    pub field_2: z2VaDY,
}
pub struct z2VVqk {
    pub field_0: z2VQAt,
}
pub struct z2VZjL(std::string::String);
impl z2VZjL {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWVn {
    pub field_0: z2VbEU,
    pub field_1: z2VZMH,
}
pub struct z2VPN6 {
    pub field_0: z2VUph,
    pub field_1: Option<z2VeNt>,
    pub field_2: Option<z2VWkd>,
}
pub struct z2VMG4 {
    pub field_0: z2VL5X,
    pub field_1: z2VRpF,
}
pub struct z2VeMQ {
    pub field_0: z2VL5X,
    pub field_1: z2VW6A,
    pub field_2: z2VMEA,
}
pub struct z2VYV1 {
    pub field_0: z2VSrE,
    pub field_1: Vec<z2VPfK>,
}
pub struct z2VNJc {
    pub field_0: z2VL5X,
}
pub struct z2VUwF {
    pub field_0: z2VUph,
    pub field_1: z2VbxF,
    pub field_2: Vec<z2VL5X>,
    pub field_3: z2Vbwi,
}
pub enum z2Vb2e {z2VVVY ( z2VSJ5 ,) , z2VMfb ( z2VYV1 ,) , z2VY7q ( z2Vd8U ,) ,} 
pub struct z2VUph(std::string::String);
impl z2VUph {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VbxF(std::string::String);
impl z2VbxF {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWHY {
    pub field_0: z2VUph,
    pub field_1: z2VZ96,
}
pub struct z2VZTd {
    pub field_0: z2VL5X,
    pub field_1: z2VdZ4,
}
pub struct z2VdKy ( z2VbxF ,) ;
pub struct z2Vb3U {
    pub field_0: z2VeKX,
}
pub enum z2VXA2 {z2VNgA ( z2VL5X ,) , z2VXZu , z2Vd25 ( z2VdZJ ,) ,} 
pub struct z2VWfb(std::string::String);
impl z2VWfb {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWk3 {
    pub field_0: z2VUph,
    pub field_1: z2VL5X,
    pub field_2: z2VcSh,
}
pub struct z2VSrv ( z2VbxF ,) ;
pub struct z2VPdA {
    pub field_0: z2VahY,
    pub field_1: z2VMEA,
    pub field_2: z2VMEA,
    pub field_3: z2VMiY,
}
pub struct z2VQY3 {
    pub field_0: z2VL5X,
    pub field_1: z2VZMH,
    pub field_2: Option<z2VaoB>,
    pub field_3: z2VVvg,
}
pub enum z2VMjw {z2VYHd , z2VVC3 , z2VSCj , z2VQj9 ,} 
pub struct z2VQFm {
    pub field_0: z2VduC,
    pub field_1: z2VSrv,
    pub field_2: z2Vf4i,
    pub field_3: Vec<z2VTRq>,
    pub field_4: Vec<z2VM44>,
    pub field_5: Vec<z2VSX9>,
    pub field_6: Vec<z2Vcoi>,
}
pub struct z2VL92 {
    pub field_0: z2VN9q,
}
pub enum z2VM1c {z2VQS6 ( z2VL5X ,) , z2VNtq , z2VaCD ( z2VS8R ,) , z2VYyM , z2VewY ,} 
pub enum z2VL5X {z2VQ5b ( z2VMEA ,) , z2VbvU ( z2VMEA ,) , z2VM9k ( z2VMEA ,) , z2VQJp ( z2VMEA ,) , z2VLPe ( z2VMEA ,) ,} 
pub enum z2VRbn {
    z2VR8C(z2VKuU),
    z2VbgE(Vec<z2VTuy>),
    z2VSh3(z2VXA2),
    z2VWbV(Vec<z2VTuy>),
    z2Vc93(z2VWfb),
    z2VcqB(z2VL5X),
}
pub struct z2VSyf(std::string::String);
impl z2VSyf {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vd8U {
    pub field_0: z2VSrE,
    pub field_1: z2VL5X,
}
pub struct z2VN9q(std::string::String);
impl z2VN9q {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VUKd(u64);
impl z2VUKd {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VbP2 {
    pub field_0: z2VUph,
    pub field_1: z2VL5X,
}
pub enum z2VRpF {z2VRtC ( z2VLn9 ,) , z2VVj1 ( z2VPDB ,) , z2VZus ( z2VduC ,) , z2VLdY ,} 
pub struct z2VdZJ ( z2VbxF ,) ;
pub struct z2VQAt {
    pub field_0: z2VUph,
    pub field_1: z2VbxF,
    pub field_2: z2VdpP,
    pub field_3: Vec<z2VL5X>,
    pub field_4: Option<z2VdVm>,
    pub field_5: Option<z2VZ96>,
    pub field_6: Option<z2VeNt>,
    pub field_7: Option<z2VWkd>,
    pub field_8: Option<z2VeNt>,
}
pub struct z2VPxW {
    pub field_0: z2VQ9E,
}
pub enum z2VLn9 {z2Vccv , z2VZ6i , z2VdH6 , z2VQ1m , z2VX3b ,} 
pub enum z2VdpP {z2VSNV , z2VVCH , z2VXkk , z2VLSs , z2VZVU , z2VMX9 , z2VcnK ,} 
pub struct z2VZcV {
    pub field_0: z2VUph,
    pub field_1: z2VL5X,
    pub field_2: z2VTRq,
}
pub struct z2VQdW {
    pub field_0: z2VSL1,
    pub field_1: z2VUfX,
    pub field_2: Vec<z2VL5X>,
}
pub struct z2VL1q {
    pub field_0: z2VN9q,
    pub field_1: z2VYwG,
    pub field_2: z2VL5X,
    pub field_3: z2VVvg,
    pub field_4: z2VVvg,
}
pub enum z2VMvf {z2VMRb , z2VWUM ,} 
pub struct z2VfB8 {
    pub field_0: z2VShF,
    pub field_1: z2Vb3i,
    pub field_2: z2VReV,
    pub field_3: z2VULF,
    pub field_4: z2VUSQ,
    pub field_5: z2Vb4P,
    pub field_6: z2VU7R,
}
pub struct z2VfEn(std::string::String);
impl z2VfEn {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNoP {
    pub field_0: z2VXpH,
    pub field_1: z2VdCT,
    pub field_2: Vec<z2VQ8r>,
}
pub enum z2VSL1 {z2VVrv , z2VNMk ,} 
pub struct z2VWkd {
    pub field_0: z2VaDY,
    pub field_1: z2VL5X,
    pub field_2: z2VMiY,
    pub field_3: Option<z2VWd1>,
    pub field_4: Option<z2VcHz>,
}
pub struct z2VMD6 {
    pub field_0: z2VWd1,
    pub field_1: z2VL5X,
}
pub struct z2VQss {
    pub field_0: z2Vevu,
    pub field_1: z2VZZu,
}
pub struct z2VcBu {
    pub field_0: z2Vevu,
    pub field_1: z2VcjD,
}
pub struct z2VYzR {
    pub field_0: z2VbEU,
}
pub struct z2VKzA {
    pub field_0: z2VbEU,
    pub field_1: z2VWd1,
}
pub struct z2VMCk {
    pub field_0: z2VMEA,
    pub field_1: z2VbxF,
    pub field_2: z2VL5X,
}
pub struct z2VWTR {
    pub field_0: z2VUph,
    pub field_1: z2VMEA,
}
pub struct z2VSrE {
    pub field_0: z2VcjD,
    pub field_1: Vec<z2VZTd>,
    pub field_2: z2VYW2,
    pub field_3: z2VMiY,
}
pub struct z2Vedi {
    pub field_0: z2VL5X,
}
pub struct z2VUQg {
    pub field_0: z2VUph,
}
pub struct z2VUSQ {
    pub field_0: z2VWd1,
    pub field_1: z2VWd1,
}
pub enum z2VZih {z2VYog , z2Vd2T , z2VXDn ( z2Vevu ,) , z2VMvz , z2VZ2M , z2VNvK ,} 
pub struct z2VdbV {
    pub field_0: z2VbxF,
    pub field_1: z2VdVm,
}
pub struct z2VbLW {
    pub field_0: z2VZMH,
    pub field_1: z2VL5X,
    pub field_2: z2VPdA,
    pub field_3: Option<z2VWd1>,
}
pub enum z2VSD2 {z2VVh1 , z2Vb5d , z2VPdE , z2VZaV , z2VLEu ,} 
pub enum z2Vb4P {z2VdJF , z2VY7Y , z2Vc1u ,} 
pub struct z2VY7s ( z2VbxF ,) ;
pub struct z2VKuU(u64);
impl z2VKuU {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VSPF {z2VY3P , z2VRgx ,} 
pub struct z2VfEW(std::string::String);
impl z2VfEW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSX9 {
    pub field_0: z2VdZJ,
    pub field_1: z2VSrv,
    pub field_2: z2VZZu,
    pub field_3: z2VY7s,
}
pub struct z2VULF(Vec<z2VfEn>);
impl z2VULF {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VfEn>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VfEn> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VfEn> {
        self.0
    }
}
pub enum z2VTLE {z2VYVT , z2VT5C , z2VM5Y ,} 
pub struct z2VdSM {
    pub field_0: z2VWaA,
    pub field_1: z2VYW2,
}
pub struct z2VWfQ {
    pub field_0: z2VQKS,
}
pub enum z2VMSL {z2VMmd , z2Vbw6 , z2VRsT , z2Ve63 , z2VP2T , z2VZzA , z2VMNG , z2Vc9J , z2Vcmp , z2VTcV , z2VeA2 ,} 
pub struct z2VVJT {
    pub field_0: z2VN9q,
    pub field_1: z2VYwG,
    pub field_2: z2Vevu,
    pub field_3: z2VaDY,
    pub field_4: z2VbTN,
}
pub enum z2VPCX {z2VZGx , z2VR7A ,} 
pub enum z2VRPH {z2VU2L , z2Vdf2 ,} 
pub enum z2VQce {z2VcYx , z2VPH9 , z2VWyL ,} 
pub struct z2VW3f {
    pub field_0: z2VfEW,
    pub field_1: z2VShF,
    pub field_2: z2VQce,
    pub field_3: z2VMvf,
    pub field_4: z2VWd1,
}
pub enum z2VYwG {z2VZBy , z2VTZk ,} 
pub struct z2VUEA {
    pub field_0: Vec<z2VPN6>,
}
pub struct z2VMh7(std::string::String);
impl z2VMh7 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWaA ( z2VbxF ,) ;
pub struct z2VLMo {
    pub field_0: z2VfEW,
    pub field_1: z2VShF,
    pub field_2: z2Vb3i,
    pub field_3: z2VcHz,
    pub field_4: z2VWd1,
    pub field_5: z2VWd1,
    pub field_6: z2Vb4P,
}
pub struct z2Va2u {
    pub field_0: z2VN9q,
    pub field_1: z2VYwG,
    pub field_2: z2Vevu,
    pub field_3: z2VNxH,
    pub field_4: z2VUfX,
    pub field_5: z2VUfX,
    pub field_6: Option<z2VQFm>,
}
pub struct z2VdVm {
    pub field_0: z2VUph,
    pub field_1: z2VaDY,
    pub field_2: z2VQdW,
    pub field_3: z2VUze,
    pub field_4: Vec<z2VTRq>,
    pub field_5: z2VL5X,
    pub field_6: z2VWd1,
    pub field_7: Option<z2VWd1>,
}
pub struct z2VT68 {
    pub field_0: Vec<z2VRPv>,
}
pub struct z2VaZo {}
pub struct z2VPqc(u64);
impl z2VPqc {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VZ96 {
    pub field_0: z2Ve1s,
    pub field_1: z2VcSh,
}
pub struct z2VSmP {
    pub field_0: z2VL5X,
    pub field_1: z2VRPH,
}
pub enum z2VcSh {z2VMNo , z2VcAF , z2VcRP , z2VbSC , z2VQS5 , z2VPm8 , z2VMTp , z2VTz2 ,} 
pub struct z2Vcoi {
    pub field_0: z2VaDY,
    pub field_1: z2VL5X,
    pub field_2: z2VTRq,
}
pub struct z2VeNt {
    pub field_0: z2Vevu,
    pub field_1: z2VaDY,
    pub field_2: z2VQFm,
}
pub struct z2VYWi {
    pub field_0: z2VSmP,
}
pub enum z2VSEb {z2VQPK ( z2Vevu ,) , z2VUAD ( z2VL5X ,) ,} 
pub struct z2VaoB {
    pub field_0: z2VL5X,
    pub field_1: z2VL5X,
    pub field_2: z2VahY,
    pub field_3: Option<z2VWd1>,
}
pub struct z2Vevu ( z2VbxF ,) ;
pub enum z2VUze {z2VRVK , z2VQyk , z2VUT3 , z2VTtp , z2VVU9 ,} 
pub struct z2VeKX(Vec<z2VfB8>);
impl z2VeKX {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VfB8>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VfB8> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VfB8> {
        self.0
    }
}
pub struct z2Vb3i(std::string::String);
impl z2Vb3i {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VbzK(std::string::String);
impl z2VbzK {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaDY {
    pub field_0: z2VduC,
    pub field_1: z2VbxF,
    pub field_2: z2VLn9,
}
pub struct z2VdCT(std::string::String);
impl z2VdCT {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VdFB {
    pub field_0: z2VMG4,
}
pub struct z2VS8R {
    pub field_0: z2VUfX,
    pub field_1: z2VUfX,
}
pub struct z2VMEA(std::string::String);
impl z2VMEA {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VL3S {
    pub field_0: z2VUfX,
    pub field_1: Vec<z2VSEb>,
}
pub enum z2VSRu {
    z2Vaoi(z2VT1M),
    z2VWtx(Vec<z2Vevu>),
    z2VR9Q(Vec<z2Vevu>),
    z2VYa2(z2VMD6),
    z2VSy2(z2VL5X),
    z2Vbxc(z2VVNR),
    z2VPaA(z2VQsx),
    z2VTbM(z2VMD6),
    z2VVb3(z2VRbn),
    z2VWTs(z2VL3S),
    z2VPyb,
}
pub struct z2VS9T {
    pub field_0: z2VXpH,
    pub field_1: z2VXpH,
    pub field_2: Option<z2VXpH>,
    pub field_3: Option<z2VdZ4>,
    pub field_4: z2VTLE,
    pub field_5: Option<z2VL5X>,
    pub field_6: Option<z2VNoP>,
    pub field_7: Option<z2VUKd>,
}
pub struct z2VYPy {
    pub field_0: Vec<z2VSmP>,
}
pub struct z2VUZ4 {
    pub field_0: z2VMSL,
}
pub struct z2VeWk {
    pub field_0: z2Vbwi,
}
pub struct z2VTXp {
    pub field_0: z2VWaA,
    pub field_1: z2VMjw,
}
pub struct z2VbEU {
    pub field_0: z2VZMH,
    pub field_1: z2VL5X,
    pub field_2: z2VVvg,
    pub field_3: z2VWd1,
    pub field_4: Option<z2VWd1>,
    pub field_5: z2VPdA,
}
pub struct z2VQKS {
    pub field_0: z2VL5X,
}
pub struct z2VULZ {
    pub field_0: Vec<z2VRPv>,
}
pub struct z2VMbZ(std::string::String);
impl z2VMbZ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VahY {z2Vcbm , z2VdbS , z2VX9u , z2VeqA , z2VeTG , z2VMWv , z2VYnt ,} 
pub struct z2VZMH {
    pub field_0: z2VbxF,
    pub field_1: z2VahY,
    pub field_2: z2VMEA,
}
pub struct z2VeqE {
    pub field_0: z2VPMJ,
    pub field_1: Option<z2VL5X>,
    pub field_2: Option<z2VWd1>,
}
pub struct z2VcjD {
    pub field_0: z2VSRu,
    pub field_1: z2VPjZ,
}
pub struct z2VPZU {
    pub field_0: z2VUph,
    pub field_1: z2VbxF,
    pub field_2: z2VMh7,
    pub field_3: z2VbzK,
    pub field_4: z2VeGX,
    pub field_5: z2VL5X,
    pub field_6: z2VL5X,
}
pub struct z2VXpH(std::string::String);
impl z2VXpH {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSiq {
    pub field_0: z2VUph,
    pub field_1: z2VWd1,
}
pub enum z2VNxH {z2VezB , z2VLZH ,} 
pub struct z2VNrA {
    pub field_0: z2VL5X,
    pub field_1: z2VdZ4,
    pub field_2: z2VW6A,
    pub field_3: z2VSD2,
    pub field_4: Option<z2VVvg>,
}
pub struct z2VU7R(u64);
impl z2VU7R {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VN3L {z2VVBx ( z2VXnX ,) , z2VTRD ( z2VWkd ,) , z2VNMG ( z2VNJc ,) , z2VLca ( z2VNrA ,) , z2Vd7d ( z2VeNt ,) , z2VPYz ( z2VdbV ,) , z2VeHA ( z2Vb2e ,) , z2VTUZ ( z2VVJT ,) , z2VYgc ( z2VUQg ,) , z2VaoE ( z2VRwp ,) , z2VWfV ( z2Vevu ,) , z2VXxG ( z2VL1q ,) , z2VcmV ( z2VcjD ,) , z2VQdc ( z2VL92 ,) , z2VTKk ( z2VWk3 ,) , z2VWcr ( z2VVC4 ,) , z2VQ4b ( z2VQcd ,) , z2VVGJ ( z2Vedi ,) , z2VSRJ ( z2Vf4i ,) , z2VXyc ( z2VeMQ ,) , z2Vcta ( z2Vbwi ,) , z2VQa4 ( z2VdtA ,) , z2VRS9 ( z2VMG4 ,) , z2VdX1 ( z2VaWD ,) , z2VdAQ ( z2VbLW ,) , z2VNMb ( z2VZcV ,) , z2VLkL ( z2VWVn ,) , z2VXMa ( z2VQKS ,) , z2VVWk ( z2VQ9E ,) , z2VMY4 ( z2VaZo ,) , z2VSM8 ( z2VUiL ,) ,} 
pub struct z2VMs1 {
    pub field_0: z2Vevu,
}
pub struct z2VUjo {
    pub field_0: z2Vb3i,
    pub field_1: z2VReV,
    pub field_2: z2VULF,
    pub field_3: z2VPqc,
    pub field_4: z2Vb4P,
    pub field_5: z2VU7R,
    pub field_6: z2VYM1,
}
pub enum z2VXKz {z2VZkW ( z2Va2u ,) , z2VSnP ( z2Va2u ,) , z2VUr9 ( z2VUEA ,) , z2VPdb ( z2VbP2 ,) , z2VTBN ( z2VeWk ,) , z2VMWf ( z2VYNR ,) , z2VMZ1 ( z2VTXp ,) , z2VcLd ( z2VdFB ,) , z2VLFu ( z2VWfQ ,) , z2VYue ( z2VdVm ,) , z2VL7Z ( z2VQ3r ,) , z2VLsJ ( z2VR27 ,) , z2VTiL ( z2VYzR ,) , z2Vbqs ( z2VeqE ,) , z2VXKB ( z2VUwF ,) , z2VMj1 ( z2VUSP ,) , z2VPpy ( z2VWTR ,) , z2Vf9K ( z2VWHY ,) , z2VYbF ( z2VSmP ,) , z2Veie ( z2VKzA ,) , z2VSeV ( z2VYPy ,) , z2Vc16 ( z2VcBu ,) , z2VPVy ( z2VPxW ,) , z2VYME ( z2VULZ ,) , z2VQJe ( z2VWvU ,) , z2VP3w ( z2VQdY ,) , z2VeMR ( z2VQss ,) , z2VY5A ( z2VSiq ,) , z2VMDs ( z2VMs1 ,) , z2VLmL ( z2VT68 ,) , z2VXcD ( z2VUZ4 ,) , z2VQdC ( z2Va2u ,) , z2VcFE ( z2Va2u ,) ,} 
pub enum z2VPjZ {z2Vcjw , z2VYj7 ( z2Vevu ,) ,} 
pub struct z2VdtA {}
pub struct z2VQ9E {
    pub field_0: z2Vevu,
    pub field_1: z2VWd1,
    pub field_2: z2VaDY,
    pub field_3: z2VRpF,
}
pub struct z2VTuy ( z2VbxF ,) ;
pub struct z2VQ3r {
    pub field_0: z2Vevu,
}
pub struct z2VeGX(std::string::String);
impl z2VeGX {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaWD {
    pub field_0: z2VMCk,
    pub field_1: z2VPdA,
}
pub struct z2VQHy(std::string::String);
impl z2VQHy {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VQ8r {
    pub field_0: z2VL5X,
    pub field_1: z2VdCT,
}
pub struct z2VPfK {
    pub field_0: z2VL5X,
    pub field_1: z2VVvg,
}
pub enum z2VduC {z2VYQn , z2VMSa , z2VemG , z2VQBv , z2VPJA , z2VSC3 , z2Vf2L ,} 
pub enum z2Ve1s {z2VWaY , z2VdAV ,} 
pub struct z2VQdY {
    pub field_0: z2VUph,
    pub field_1: z2VL5X,
}
pub struct z2VUSP {
    pub field_0: Vec<z2VQAt>,
}
pub struct z2VWvU {
    pub field_0: z2VZih,
}
pub struct z2VWd1(u64);
impl z2VWd1 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VRAT {
    pub field_0: z2VVmW,
}
pub struct z2VQcd {
    pub field_0: z2VN9q,
    pub field_1: z2VYwG,
    pub field_2: z2Vevu,
    pub field_3: z2VaDY,
    pub field_4: z2VP1D,
    pub field_5: z2VL5X,
}
pub struct z2VYM8 {
    pub field_0: z2VaDY,
    pub field_1: Vec<z2VL5X>,
    pub field_2: Vec<z2VL5X>,
}
pub struct z2VReV {
    pub field_0: z2VMbZ,
}
pub struct z2VXnX {
    pub field_0: z2VPZU,
    pub field_1: z2VL5X,
}
pub struct z2VYNR {
    pub field_0: z2VdZ4,
}
pub struct z2VW6A(std::string::String);
impl z2VW6A {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VT1M {
    pub field_0: z2VWd1,
    pub field_1: z2VL3S,
    pub field_2: z2VL3S,
}
pub struct z2VbTN {
    pub field_0: z2VWd1,
    pub field_1: z2VWd1,
}
pub struct z2VShF(std::string::String);
impl z2VShF {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSGX {
    pub field_0: z2VfEW,
    pub field_1: z2VSPF,
}
pub struct z2VXWs {
    pub field_0: z2VShF,
}
pub struct z2Vbwi {
    pub field_0: z2VUph,
}
pub enum z2VYW2 {z2VVkq ,} 
pub struct z2VRwp {
    pub field_0: z2VZMH,
    pub field_1: z2VL5X,
    pub field_2: z2VPdA,
}
pub struct z2VM44 {
    pub field_0: z2VbxF,
    pub field_1: z2VbxF,
    pub field_2: z2VL5X,
    pub field_3: z2VTRq,
}
