// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DaemonPath(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PrincipalName(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PrincipalId(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PublicKeyFingerprint(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BlsPublicKey(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BlsSignature(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObjectDigest(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplayNonce(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContractName(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationRequestSlot(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationScope(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContractOperationHead(pub String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanos(pub Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequiredSignatureThreshold(pub Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SignatureScheme {
    Bls12_381MinPk,
    Bls12_381MinSig,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PrincipalStatus {
    Active,
    Revoked,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum KeyPurpose {
    CriomeRoot,
    PersonaRequest,
    AgentRequest,
    ReleaseAuthorization,
    HostPublication,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ContentPurpose {
    SignedObject,
    ComponentRelease,
    ChannelGrant,
    ChannelRetract,
    Authorization,
    Archive,
    PrivilegeElevation,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum VerificationDecision {
    Valid,
    InvalidSignature,
    UnknownSigner,
    Expired,
    Revoked,
    ReplayAttempted,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SignatureAuthorizationResult {
    SingleSignature,
    RequiredSignaturesSatisfied,
    PendingSignatures,
    Rejected,
    Expired,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AuthorizationPolicyClass {
    SimpleSelfSigned,
    ComplexQuorum,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AuthorizationStatus {
    Pending,
    Signing,
    Granted,
    Denied,
    Expired,
    Unavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AuthorizationDenialReason {
    PolicyRefused,
    RequiredSignatureMissing,
    SignatureRejected,
    SignerThresholdRejected,
    SignatureExpired,
    RequestDigestMismatch,
    SignatureScopeMismatch,
    SignerUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AuthorizationDenialSource {
    Policy,
    Signers,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    MalformedRequest,
    UnsupportedSignatureScheme,
    UnknownIdentity,
    RevokedIdentity,
    DuplicateIdentity,
    ReplayAttempted,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Identity {
    Persona(PrincipalName),
    Agent(PrincipalName),
    Host(PrincipalName),
    Developer(PrincipalName),
    Cluster(PrincipalName),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CriomeDaemonConfiguration {
    pub socket_path: DaemonPath,
    pub store_path: DaemonPath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationPolicySatisfaction {
    pub policy_class: AuthorizationPolicyClass,
    pub required_signature_threshold: RequiredSignatureThreshold,
    pub satisfied_signers: Vec<Identity>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationDenial {
    pub source: AuthorizationDenialSource,
    pub reason: AuthorizationDenialReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContentReference {
    pub digest: ObjectDigest,
    pub purpose: ContentPurpose,
    pub schema_version: PrincipalName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuditContext {
    pub purpose: ContentPurpose,
    pub audience: PrincipalName,
    pub policy_version: PrincipalName,
    pub nonce: ReplayNonce,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignatureEnvelope {
    pub scheme: SignatureScheme,
    pub public_key: BlsPublicKey,
    pub signature: BlsSignature,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Attestation {
    pub content: ContentReference,
    pub signer: Identity,
    pub envelope: SignatureEnvelope,
    pub issued_at: TimestampNanos,
    pub expires_at: Option<TimestampNanos>,
    pub audit_context: AuditContext,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignedObject {
    pub content: ContentReference,
    pub signer: Identity,
    pub envelope: SignatureEnvelope,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationGrant {
    pub issuer: Identity,
    pub subject: Identity,
    pub scope: ContentPurpose,
    pub expires_at: Option<TimestampNanos>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentRelease {
    pub component: PrincipalName,
    pub artifact: ObjectDigest,
    pub authorized_by: Identity,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignedPersonaRequest {
    pub audience: Identity,
    pub content: ContentReference,
    pub delegation: Option<DelegationGrant>,
    pub envelope: SignatureEnvelope,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalCallAuthorization {
    pub request_digest: ObjectDigest,
    pub contract: ContractName,
    pub operation: ContractOperationHead,
    pub scope: AuthorizationScope,
    pub requester: Identity,
    pub nonce: ReplayNonce,
    pub expires_at: Option<TimestampNanos>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationObservation(pub AuthorizationRequestSlot);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationVerification {
    pub request_digest: ObjectDigest,
    pub authorization: AuthorizationGrant,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignatureSolicitation {
    pub request_slot: AuthorizationRequestSlot,
    pub request_digest: ObjectDigest,
    pub contract: ContractName,
    pub operation: ContractOperationHead,
    pub scope: AuthorizationScope,
    pub requester: Identity,
    pub required_signer: Identity,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignatureSolicitationRoute {
    pub solicitation: SignatureSolicitation,
    pub routed_to: Identity,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignatureSubmission {
    pub request_slot: AuthorizationRequestSlot,
    pub signer: Identity,
    pub envelope: SignatureEnvelope,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationRejection {
    pub request_slot: AuthorizationRequestSlot,
    pub rejector: Identity,
    pub reason: AuthorizationDenialReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationGrant {
    pub request_slot: AuthorizationRequestSlot,
    pub authorized_object_digest: ObjectDigest,
    pub authorized_contract: ContractName,
    pub authorized_operation: ContractOperationHead,
    pub authorization_scope: AuthorizationScope,
    pub policy_satisfaction: AuthorizationPolicySatisfaction,
    pub signature_result: SignatureAuthorizationResult,
    pub signatures: Vec<SignatureEnvelope>,
    pub issued_by: Identity,
    pub issued_at: TimestampNanos,
    pub expires_at: Option<TimestampNanos>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationObservationToken(pub AuthorizationRequestSlot);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationPending {
    pub request_slot: AuthorizationRequestSlot,
    pub request_digest: ObjectDigest,
    pub missing_authorities: Vec<Identity>,
    pub observation_token: AuthorizationObservationToken,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationDenied {
    pub request_slot: AuthorizationRequestSlot,
    pub denial: AuthorizationDenial,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationExpired {
    pub request_slot: AuthorizationRequestSlot,
    pub expired_at: TimestampNanos,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationUnavailable {
    pub request_slot: AuthorizationRequestSlot,
    pub reason: PrincipalName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationStateRecord {
    pub request_slot: AuthorizationRequestSlot,
    pub request_digest: ObjectDigest,
    pub status: AuthorizationStatus,
    pub missing_authorities: Vec<Identity>,
    pub grant: Option<AuthorizationGrant>,
    pub denial: Option<AuthorizationDenial>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationObservationSnapshot(pub Vec<AuthorizationStateRecord>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignatureRouteReceipt {
    pub request_slot: AuthorizationRequestSlot,
    pub routed_to: Identity,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignatureSubmissionReceipt {
    pub request_slot: AuthorizationRequestSlot,
    pub signer: Identity,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationObservationRetracted(pub AuthorizationObservationToken);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationUpdate(pub AuthorizationStateRecord);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignRequest {
    pub content: ContentReference,
    pub signer: Identity,
    pub audit_context: AuditContext,
    pub expires_at: Option<TimestampNanos>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VerifyRequest {
    pub attestation: Attestation,
    pub content: ContentReference,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentityRegistration {
    pub identity: Identity,
    pub public_key: BlsPublicKey,
    pub fingerprint: PublicKeyFingerprint,
    pub purpose: KeyPurpose,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentityRevocation {
    pub identity: Identity,
    pub fingerprint: PublicKeyFingerprint,
    pub reason: PrincipalName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentityLookup(pub Identity);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArchiveAttestationRequest {
    pub release: ComponentRelease,
    pub audit_context: AuditContext,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelGrantAttestationRequest {
    pub grant_content: ContentReference,
    pub source: Identity,
    pub audit_context: AuditContext,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationAttestationRequest {
    pub authorization_content: ContentReference,
    pub source: Identity,
    pub audit_context: AuditContext,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentitySubscription(pub Identity);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentitySubscriptionToken(pub Identity);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignReceipt {
    pub attestation: Attestation,
    pub issued_at: TimestampNanos,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VerificationResult {
    pub decision: VerificationDecision,
    pub identity: Option<Identity>,
    pub expires_at: Option<TimestampNanos>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentityReceipt {
    pub identity: Identity,
    pub status: PrincipalStatus,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentitySnapshot(pub Vec<IdentityReceipt>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AttestationReceipt(pub Attestation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IdentityUpdate(pub IdentityReceipt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionRetracted(pub IdentitySubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejection(pub RejectionReason);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CriomeEvent {
    IdentityUpdate(IdentityUpdate),
    AuthorizationUpdate(AuthorizationUpdate),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Sign(SignRequest),
    VerifyAttestation(VerifyRequest),
    RegisterIdentity(IdentityRegistration),
    RevokeIdentity(IdentityRevocation),
    LookupIdentity(IdentityLookup),
    AttestArchive(ArchiveAttestationRequest),
    AttestChannelGrant(ChannelGrantAttestationRequest),
    AttestAuthorization(AuthorizationAttestationRequest),
    AuthorizeSignalCall(SignalCallAuthorization),
    ObserveAuthorization(AuthorizationObservation),
    VerifyAuthorization(AuthorizationVerification),
    RouteSignatureRequest(SignatureSolicitationRoute),
    SubmitSignature(SignatureSubmission),
    RejectAuthorization(AuthorizationRejection),
    SubscribeIdentityUpdates(IdentitySubscription),
    IdentitySubscriptionRetraction(IdentitySubscriptionToken),
    AuthorizationObservationRetraction(AuthorizationObservationToken),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SignReceipt(SignReceipt),
    VerificationResult(VerificationResult),
    IdentityReceipt(IdentityReceipt),
    IdentitySnapshot(IdentitySnapshot),
    AttestationReceipt(AttestationReceipt),
    AuthorizationPending(AuthorizationPending),
    AuthorizationGranted(AuthorizationGrant),
    AuthorizationDenied(AuthorizationDenied),
    AuthorizationExpired(AuthorizationExpired),
    AuthorizationUnavailable(AuthorizationUnavailable),
    AuthorizationObservationSnapshot(AuthorizationObservationSnapshot),
    SignatureRouteReceipt(SignatureRouteReceipt),
    SignatureSubmissionReceipt(SignatureSubmissionReceipt),
    AuthorizationObservationRetracted(AuthorizationObservationRetracted),
    SubscriptionRetracted(SubscriptionRetracted),
    Rejection(Rejection),
}

#[rustfmt::skip]
impl DaemonPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DaemonPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PrincipalName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PrincipalName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PrincipalId {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PrincipalId {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PublicKeyFingerprint {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PublicKeyFingerprint {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BlsPublicKey {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for BlsPublicKey {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BlsSignature {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for BlsSignature {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObjectDigest {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ObjectDigest {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplayNonce {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ReplayNonce {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContractName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ContractName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizationRequestSlot {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AuthorizationRequestSlot {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizationScope {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AuthorizationScope {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContractOperationHead {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ContractOperationHead {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanos {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TimestampNanos {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequiredSignatureThreshold {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for RequiredSignatureThreshold {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizationObservation {
    pub fn new(payload: AuthorizationRequestSlot) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AuthorizationRequestSlot {
        &self.0
    }
    pub fn into_payload(self) -> AuthorizationRequestSlot {
        self.0
    }
}
#[rustfmt::skip]
impl From<AuthorizationRequestSlot> for AuthorizationObservation {
    fn from(payload: AuthorizationRequestSlot) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizationObservationToken {
    pub fn new(payload: AuthorizationRequestSlot) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AuthorizationRequestSlot {
        &self.0
    }
    pub fn into_payload(self) -> AuthorizationRequestSlot {
        self.0
    }
}
#[rustfmt::skip]
impl From<AuthorizationRequestSlot> for AuthorizationObservationToken {
    fn from(payload: AuthorizationRequestSlot) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizationObservationSnapshot {
    pub fn new(payload: Vec<AuthorizationStateRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<AuthorizationStateRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<AuthorizationStateRecord> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<AuthorizationStateRecord>> for AuthorizationObservationSnapshot {
    fn from(payload: Vec<AuthorizationStateRecord>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizationObservationRetracted {
    pub fn new(payload: AuthorizationObservationToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AuthorizationObservationToken {
        &self.0
    }
    pub fn into_payload(self) -> AuthorizationObservationToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<AuthorizationObservationToken> for AuthorizationObservationRetracted {
    fn from(payload: AuthorizationObservationToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizationUpdate {
    pub fn new(payload: AuthorizationStateRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AuthorizationStateRecord {
        &self.0
    }
    pub fn into_payload(self) -> AuthorizationStateRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<AuthorizationStateRecord> for AuthorizationUpdate {
    fn from(payload: AuthorizationStateRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IdentityLookup {
    pub fn new(payload: Identity) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Identity {
        &self.0
    }
    pub fn into_payload(self) -> Identity {
        self.0
    }
}
#[rustfmt::skip]
impl From<Identity> for IdentityLookup {
    fn from(payload: Identity) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IdentitySubscription {
    pub fn new(payload: Identity) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Identity {
        &self.0
    }
    pub fn into_payload(self) -> Identity {
        self.0
    }
}
#[rustfmt::skip]
impl From<Identity> for IdentitySubscription {
    fn from(payload: Identity) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IdentitySubscriptionToken {
    pub fn new(payload: Identity) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Identity {
        &self.0
    }
    pub fn into_payload(self) -> Identity {
        self.0
    }
}
#[rustfmt::skip]
impl From<Identity> for IdentitySubscriptionToken {
    fn from(payload: Identity) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IdentitySnapshot {
    pub fn new(payload: Vec<IdentityReceipt>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<IdentityReceipt> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<IdentityReceipt> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<IdentityReceipt>> for IdentitySnapshot {
    fn from(payload: Vec<IdentityReceipt>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AttestationReceipt {
    pub fn new(payload: Attestation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Attestation {
        &self.0
    }
    pub fn into_payload(self) -> Attestation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Attestation> for AttestationReceipt {
    fn from(payload: Attestation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IdentityUpdate {
    pub fn new(payload: IdentityReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &IdentityReceipt {
        &self.0
    }
    pub fn into_payload(self) -> IdentityReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<IdentityReceipt> for IdentityUpdate {
    fn from(payload: IdentityReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionRetracted {
    pub fn new(payload: IdentitySubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &IdentitySubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> IdentitySubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<IdentitySubscriptionToken> for SubscriptionRetracted {
    fn from(payload: IdentitySubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Rejection {
    pub fn new(payload: RejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> RejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectionReason> for Rejection {
    fn from(payload: RejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Identity {
    pub fn persona(payload: String) -> Self {
        Self::Persona(PrincipalName::new(payload))
    }
    pub fn agent(payload: String) -> Self {
        Self::Agent(PrincipalName::new(payload))
    }
    pub fn host(payload: String) -> Self {
        Self::Host(PrincipalName::new(payload))
    }
    pub fn developer(payload: String) -> Self {
        Self::Developer(PrincipalName::new(payload))
    }
    pub fn cluster(payload: String) -> Self {
        Self::Cluster(PrincipalName::new(payload))
    }
}

#[rustfmt::skip]
impl CriomeEvent {
    pub fn identity_update(payload: IdentityReceipt) -> Self {
        Self::IdentityUpdate(IdentityUpdate::new(payload))
    }
    pub fn authorization_update(payload: AuthorizationStateRecord) -> Self {
        Self::AuthorizationUpdate(AuthorizationUpdate::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn sign(payload: SignRequest) -> Self {
        Self::Sign(payload)
    }
    pub fn verify_attestation(payload: VerifyRequest) -> Self {
        Self::VerifyAttestation(payload)
    }
    pub fn register_identity(payload: IdentityRegistration) -> Self {
        Self::RegisterIdentity(payload)
    }
    pub fn revoke_identity(payload: IdentityRevocation) -> Self {
        Self::RevokeIdentity(payload)
    }
    pub fn lookup_identity(payload: Identity) -> Self {
        Self::LookupIdentity(IdentityLookup::new(payload))
    }
    pub fn attest_archive(payload: ArchiveAttestationRequest) -> Self {
        Self::AttestArchive(payload)
    }
    pub fn attest_channel_grant(payload: ChannelGrantAttestationRequest) -> Self {
        Self::AttestChannelGrant(payload)
    }
    pub fn attest_authorization(payload: AuthorizationAttestationRequest) -> Self {
        Self::AttestAuthorization(payload)
    }
    pub fn authorize_signal_call(payload: SignalCallAuthorization) -> Self {
        Self::AuthorizeSignalCall(payload)
    }
    pub fn observe_authorization(payload: AuthorizationRequestSlot) -> Self {
        Self::ObserveAuthorization(AuthorizationObservation::new(payload))
    }
    pub fn verify_authorization(payload: AuthorizationVerification) -> Self {
        Self::VerifyAuthorization(payload)
    }
    pub fn route_signature_request(payload: SignatureSolicitationRoute) -> Self {
        Self::RouteSignatureRequest(payload)
    }
    pub fn submit_signature(payload: SignatureSubmission) -> Self {
        Self::SubmitSignature(payload)
    }
    pub fn reject_authorization(payload: AuthorizationRejection) -> Self {
        Self::RejectAuthorization(payload)
    }
    pub fn subscribe_identity_updates(payload: Identity) -> Self {
        Self::SubscribeIdentityUpdates(IdentitySubscription::new(payload))
    }
    pub fn identity_subscription_retraction(payload: Identity) -> Self {
        Self::IdentitySubscriptionRetraction(IdentitySubscriptionToken::new(payload))
    }
    pub fn authorization_observation_retraction(
        payload: AuthorizationRequestSlot,
    ) -> Self {
        Self::AuthorizationObservationRetraction(
            AuthorizationObservationToken::new(payload),
        )
    }
}

#[rustfmt::skip]
impl Output {
    pub fn sign_receipt(payload: SignReceipt) -> Self {
        Self::SignReceipt(payload)
    }
    pub fn verification_result(payload: VerificationResult) -> Self {
        Self::VerificationResult(payload)
    }
    pub fn identity_receipt(payload: IdentityReceipt) -> Self {
        Self::IdentityReceipt(payload)
    }
    pub fn identity_snapshot(payload: Vec<IdentityReceipt>) -> Self {
        Self::IdentitySnapshot(IdentitySnapshot::new(payload))
    }
    pub fn attestation_receipt(payload: Attestation) -> Self {
        Self::AttestationReceipt(AttestationReceipt::new(payload))
    }
    pub fn authorization_pending(payload: AuthorizationPending) -> Self {
        Self::AuthorizationPending(payload)
    }
    pub fn authorization_granted(payload: AuthorizationGrant) -> Self {
        Self::AuthorizationGranted(payload)
    }
    pub fn authorization_denied(payload: AuthorizationDenied) -> Self {
        Self::AuthorizationDenied(payload)
    }
    pub fn authorization_expired(payload: AuthorizationExpired) -> Self {
        Self::AuthorizationExpired(payload)
    }
    pub fn authorization_unavailable(payload: AuthorizationUnavailable) -> Self {
        Self::AuthorizationUnavailable(payload)
    }
    pub fn authorization_observation_snapshot(
        payload: Vec<AuthorizationStateRecord>,
    ) -> Self {
        Self::AuthorizationObservationSnapshot(
            AuthorizationObservationSnapshot::new(payload),
        )
    }
    pub fn signature_route_receipt(payload: SignatureRouteReceipt) -> Self {
        Self::SignatureRouteReceipt(payload)
    }
    pub fn signature_submission_receipt(payload: SignatureSubmissionReceipt) -> Self {
        Self::SignatureSubmissionReceipt(payload)
    }
    pub fn authorization_observation_retracted(
        payload: AuthorizationObservationToken,
    ) -> Self {
        Self::AuthorizationObservationRetracted(
            AuthorizationObservationRetracted::new(payload),
        )
    }
    pub fn subscription_retracted(payload: IdentitySubscriptionToken) -> Self {
        Self::SubscriptionRetracted(SubscriptionRetracted::new(payload))
    }
    pub fn rejection(payload: RejectionReason) -> Self {
        Self::Rejection(Rejection::new(payload))
    }
}

#[rustfmt::skip]
impl From<IdentityUpdate> for CriomeEvent {
    fn from(payload: IdentityUpdate) -> Self {
        Self::IdentityUpdate(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationUpdate> for CriomeEvent {
    fn from(payload: AuthorizationUpdate) -> Self {
        Self::AuthorizationUpdate(payload)
    }
}

#[rustfmt::skip]
impl From<SignRequest> for Input {
    fn from(payload: SignRequest) -> Self {
        Self::Sign(payload)
    }
}

#[rustfmt::skip]
impl From<VerifyRequest> for Input {
    fn from(payload: VerifyRequest) -> Self {
        Self::VerifyAttestation(payload)
    }
}

#[rustfmt::skip]
impl From<IdentityRegistration> for Input {
    fn from(payload: IdentityRegistration) -> Self {
        Self::RegisterIdentity(payload)
    }
}

#[rustfmt::skip]
impl From<IdentityRevocation> for Input {
    fn from(payload: IdentityRevocation) -> Self {
        Self::RevokeIdentity(payload)
    }
}

#[rustfmt::skip]
impl From<IdentityLookup> for Input {
    fn from(payload: IdentityLookup) -> Self {
        Self::LookupIdentity(payload)
    }
}

#[rustfmt::skip]
impl From<ArchiveAttestationRequest> for Input {
    fn from(payload: ArchiveAttestationRequest) -> Self {
        Self::AttestArchive(payload)
    }
}

#[rustfmt::skip]
impl From<ChannelGrantAttestationRequest> for Input {
    fn from(payload: ChannelGrantAttestationRequest) -> Self {
        Self::AttestChannelGrant(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationAttestationRequest> for Input {
    fn from(payload: AuthorizationAttestationRequest) -> Self {
        Self::AttestAuthorization(payload)
    }
}

#[rustfmt::skip]
impl From<SignalCallAuthorization> for Input {
    fn from(payload: SignalCallAuthorization) -> Self {
        Self::AuthorizeSignalCall(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationObservation> for Input {
    fn from(payload: AuthorizationObservation) -> Self {
        Self::ObserveAuthorization(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationVerification> for Input {
    fn from(payload: AuthorizationVerification) -> Self {
        Self::VerifyAuthorization(payload)
    }
}

#[rustfmt::skip]
impl From<SignatureSolicitationRoute> for Input {
    fn from(payload: SignatureSolicitationRoute) -> Self {
        Self::RouteSignatureRequest(payload)
    }
}

#[rustfmt::skip]
impl From<SignatureSubmission> for Input {
    fn from(payload: SignatureSubmission) -> Self {
        Self::SubmitSignature(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationRejection> for Input {
    fn from(payload: AuthorizationRejection) -> Self {
        Self::RejectAuthorization(payload)
    }
}

#[rustfmt::skip]
impl From<IdentitySubscription> for Input {
    fn from(payload: IdentitySubscription) -> Self {
        Self::SubscribeIdentityUpdates(payload)
    }
}

#[rustfmt::skip]
impl From<IdentitySubscriptionToken> for Input {
    fn from(payload: IdentitySubscriptionToken) -> Self {
        Self::IdentitySubscriptionRetraction(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationObservationToken> for Input {
    fn from(payload: AuthorizationObservationToken) -> Self {
        Self::AuthorizationObservationRetraction(payload)
    }
}

#[rustfmt::skip]
impl From<SignReceipt> for Output {
    fn from(payload: SignReceipt) -> Self {
        Self::SignReceipt(payload)
    }
}

#[rustfmt::skip]
impl From<VerificationResult> for Output {
    fn from(payload: VerificationResult) -> Self {
        Self::VerificationResult(payload)
    }
}

#[rustfmt::skip]
impl From<IdentityReceipt> for Output {
    fn from(payload: IdentityReceipt) -> Self {
        Self::IdentityReceipt(payload)
    }
}

#[rustfmt::skip]
impl From<IdentitySnapshot> for Output {
    fn from(payload: IdentitySnapshot) -> Self {
        Self::IdentitySnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<AttestationReceipt> for Output {
    fn from(payload: AttestationReceipt) -> Self {
        Self::AttestationReceipt(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationPending> for Output {
    fn from(payload: AuthorizationPending) -> Self {
        Self::AuthorizationPending(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationGrant> for Output {
    fn from(payload: AuthorizationGrant) -> Self {
        Self::AuthorizationGranted(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationDenied> for Output {
    fn from(payload: AuthorizationDenied) -> Self {
        Self::AuthorizationDenied(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationExpired> for Output {
    fn from(payload: AuthorizationExpired) -> Self {
        Self::AuthorizationExpired(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationUnavailable> for Output {
    fn from(payload: AuthorizationUnavailable) -> Self {
        Self::AuthorizationUnavailable(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationObservationSnapshot> for Output {
    fn from(payload: AuthorizationObservationSnapshot) -> Self {
        Self::AuthorizationObservationSnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<SignatureRouteReceipt> for Output {
    fn from(payload: SignatureRouteReceipt) -> Self {
        Self::SignatureRouteReceipt(payload)
    }
}

#[rustfmt::skip]
impl From<SignatureSubmissionReceipt> for Output {
    fn from(payload: SignatureSubmissionReceipt) -> Self {
        Self::SignatureSubmissionReceipt(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationObservationRetracted> for Output {
    fn from(payload: AuthorizationObservationRetracted) -> Self {
        Self::AuthorizationObservationRetracted(payload)
    }
}

#[rustfmt::skip]
impl From<SubscriptionRetracted> for Output {
    fn from(payload: SubscriptionRetracted) -> Self {
        Self::SubscriptionRetracted(payload)
    }
}

#[rustfmt::skip]
impl From<Rejection> for Output {
    fn from(payload: Rejection) -> Self {
        Self::Rejection(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DaemonPath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PrincipalName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PrincipalId {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PublicKeyFingerprint {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl BlsPublicKey {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl BlsSignature {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObjectDigest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReplayNonce {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ContractName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationRequestSlot {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationScope {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ContractOperationHead {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TimestampNanos {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RequiredSignatureThreshold {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureScheme {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PrincipalStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl KeyPurpose {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ContentPurpose {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl VerificationDecision {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureAuthorizationResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationPolicyClass {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationDenialReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationDenialSource {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Identity {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CriomeDaemonConfiguration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationPolicySatisfaction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationDenial {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ContentReference {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuditContext {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureEnvelope {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Attestation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignedObject {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DelegationGrant {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ComponentRelease {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignedPersonaRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignalCallAuthorization {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationObservation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationVerification {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureSolicitation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureSolicitationRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureSubmission {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationGrant {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationObservationToken {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationPending {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationDenied {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationExpired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationUnavailable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationStateRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationObservationSnapshot {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureRouteReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignatureSubmissionReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationObservationRetracted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationUpdate {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl VerifyRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentityRegistration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentityRevocation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentityLookup {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ArchiveAttestationRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ChannelGrantAttestationRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AuthorizationAttestationRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentitySubscription {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentitySubscriptionToken {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl VerificationResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentityReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentitySnapshot {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AttestationReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl IdentityUpdate {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SubscriptionRetracted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Rejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CriomeEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_SIGN: u64 = 0x0000000000000000;
    pub const INPUT_VERIFY_ATTESTATION: u64 = 0x0001000000000000;
    pub const INPUT_REGISTER_IDENTITY: u64 = 0x0002000000000000;
    pub const INPUT_REVOKE_IDENTITY: u64 = 0x0003000000000000;
    pub const INPUT_LOOKUP_IDENTITY: u64 = 0x0004000000000000;
    pub const INPUT_ATTEST_ARCHIVE: u64 = 0x0005000000000000;
    pub const INPUT_ATTEST_CHANNEL_GRANT: u64 = 0x0006000000000000;
    pub const INPUT_ATTEST_AUTHORIZATION: u64 = 0x0007000000000000;
    pub const INPUT_AUTHORIZE_SIGNAL_CALL: u64 = 0x0008000000000000;
    pub const INPUT_OBSERVE_AUTHORIZATION: u64 = 0x0009000000000000;
    pub const INPUT_VERIFY_AUTHORIZATION: u64 = 0x000A000000000000;
    pub const INPUT_ROUTE_SIGNATURE_REQUEST: u64 = 0x000B000000000000;
    pub const INPUT_SUBMIT_SIGNATURE: u64 = 0x000C000000000000;
    pub const INPUT_REJECT_AUTHORIZATION: u64 = 0x000D000000000000;
    pub const INPUT_SUBSCRIBE_IDENTITY_UPDATES: u64 = 0x000E000000000000;
    pub const INPUT_IDENTITY_SUBSCRIPTION_RETRACTION: u64 = 0x000F000000000000;
    pub const INPUT_AUTHORIZATION_OBSERVATION_RETRACTION: u64 = 0x0010000000000000;
    pub const OUTPUT_SIGN_RECEIPT: u64 = 0x0100000000000000;
    pub const OUTPUT_VERIFICATION_RESULT: u64 = 0x0101000000000000;
    pub const OUTPUT_IDENTITY_RECEIPT: u64 = 0x0102000000000000;
    pub const OUTPUT_IDENTITY_SNAPSHOT: u64 = 0x0103000000000000;
    pub const OUTPUT_ATTESTATION_RECEIPT: u64 = 0x0104000000000000;
    pub const OUTPUT_AUTHORIZATION_PENDING: u64 = 0x0105000000000000;
    pub const OUTPUT_AUTHORIZATION_GRANTED: u64 = 0x0106000000000000;
    pub const OUTPUT_AUTHORIZATION_DENIED: u64 = 0x0107000000000000;
    pub const OUTPUT_AUTHORIZATION_EXPIRED: u64 = 0x0108000000000000;
    pub const OUTPUT_AUTHORIZATION_UNAVAILABLE: u64 = 0x0109000000000000;
    pub const OUTPUT_AUTHORIZATION_OBSERVATION_SNAPSHOT: u64 = 0x010A000000000000;
    pub const OUTPUT_SIGNATURE_ROUTE_RECEIPT: u64 = 0x010B000000000000;
    pub const OUTPUT_SIGNATURE_SUBMISSION_RECEIPT: u64 = 0x010C000000000000;
    pub const OUTPUT_AUTHORIZATION_OBSERVATION_RETRACTED: u64 = 0x010D000000000000;
    pub const OUTPUT_SUBSCRIPTION_RETRACTED: u64 = 0x010E000000000000;
    pub const OUTPUT_REJECTION: u64 = 0x010F000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Sign,
    VerifyAttestation,
    RegisterIdentity,
    RevokeIdentity,
    LookupIdentity,
    AttestArchive,
    AttestChannelGrant,
    AttestAuthorization,
    AuthorizeSignalCall,
    ObserveAuthorization,
    VerifyAuthorization,
    RouteSignatureRequest,
    SubmitSignature,
    RejectAuthorization,
    SubscribeIdentityUpdates,
    IdentitySubscriptionRetraction,
    AuthorizationObservationRetraction,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    SignReceipt,
    VerificationResult,
    IdentityReceipt,
    IdentitySnapshot,
    AttestationReceipt,
    AuthorizationPending,
    AuthorizationGranted,
    AuthorizationDenied,
    AuthorizationExpired,
    AuthorizationUnavailable,
    AuthorizationObservationSnapshot,
    SignatureRouteReceipt,
    SignatureSubmissionReceipt,
    AuthorizationObservationRetracted,
    SubscriptionRetracted,
    Rejection,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Sign(_) => InputRoute::Sign,
            Self::VerifyAttestation(_) => InputRoute::VerifyAttestation,
            Self::RegisterIdentity(_) => InputRoute::RegisterIdentity,
            Self::RevokeIdentity(_) => InputRoute::RevokeIdentity,
            Self::LookupIdentity(_) => InputRoute::LookupIdentity,
            Self::AttestArchive(_) => InputRoute::AttestArchive,
            Self::AttestChannelGrant(_) => InputRoute::AttestChannelGrant,
            Self::AttestAuthorization(_) => InputRoute::AttestAuthorization,
            Self::AuthorizeSignalCall(_) => InputRoute::AuthorizeSignalCall,
            Self::ObserveAuthorization(_) => InputRoute::ObserveAuthorization,
            Self::VerifyAuthorization(_) => InputRoute::VerifyAuthorization,
            Self::RouteSignatureRequest(_) => InputRoute::RouteSignatureRequest,
            Self::SubmitSignature(_) => InputRoute::SubmitSignature,
            Self::RejectAuthorization(_) => InputRoute::RejectAuthorization,
            Self::SubscribeIdentityUpdates(_) => InputRoute::SubscribeIdentityUpdates,
            Self::IdentitySubscriptionRetraction(_) => {
                InputRoute::IdentitySubscriptionRetraction
            }
            Self::AuthorizationObservationRetraction(_) => {
                InputRoute::AuthorizationObservationRetraction
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Sign(_) => short_header::INPUT_SIGN,
            Self::VerifyAttestation(_) => short_header::INPUT_VERIFY_ATTESTATION,
            Self::RegisterIdentity(_) => short_header::INPUT_REGISTER_IDENTITY,
            Self::RevokeIdentity(_) => short_header::INPUT_REVOKE_IDENTITY,
            Self::LookupIdentity(_) => short_header::INPUT_LOOKUP_IDENTITY,
            Self::AttestArchive(_) => short_header::INPUT_ATTEST_ARCHIVE,
            Self::AttestChannelGrant(_) => short_header::INPUT_ATTEST_CHANNEL_GRANT,
            Self::AttestAuthorization(_) => short_header::INPUT_ATTEST_AUTHORIZATION,
            Self::AuthorizeSignalCall(_) => short_header::INPUT_AUTHORIZE_SIGNAL_CALL,
            Self::ObserveAuthorization(_) => short_header::INPUT_OBSERVE_AUTHORIZATION,
            Self::VerifyAuthorization(_) => short_header::INPUT_VERIFY_AUTHORIZATION,
            Self::RouteSignatureRequest(_) => short_header::INPUT_ROUTE_SIGNATURE_REQUEST,
            Self::SubmitSignature(_) => short_header::INPUT_SUBMIT_SIGNATURE,
            Self::RejectAuthorization(_) => short_header::INPUT_REJECT_AUTHORIZATION,
            Self::SubscribeIdentityUpdates(_) => {
                short_header::INPUT_SUBSCRIBE_IDENTITY_UPDATES
            }
            Self::IdentitySubscriptionRetraction(_) => {
                short_header::INPUT_IDENTITY_SUBSCRIPTION_RETRACTION
            }
            Self::AuthorizationObservationRetraction(_) => {
                short_header::INPUT_AUTHORIZATION_OBSERVATION_RETRACTION
            }
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_SIGN => Ok(InputRoute::Sign),
            short_header::INPUT_VERIFY_ATTESTATION => Ok(InputRoute::VerifyAttestation),
            short_header::INPUT_REGISTER_IDENTITY => Ok(InputRoute::RegisterIdentity),
            short_header::INPUT_REVOKE_IDENTITY => Ok(InputRoute::RevokeIdentity),
            short_header::INPUT_LOOKUP_IDENTITY => Ok(InputRoute::LookupIdentity),
            short_header::INPUT_ATTEST_ARCHIVE => Ok(InputRoute::AttestArchive),
            short_header::INPUT_ATTEST_CHANNEL_GRANT => {
                Ok(InputRoute::AttestChannelGrant)
            }
            short_header::INPUT_ATTEST_AUTHORIZATION => {
                Ok(InputRoute::AttestAuthorization)
            }
            short_header::INPUT_AUTHORIZE_SIGNAL_CALL => {
                Ok(InputRoute::AuthorizeSignalCall)
            }
            short_header::INPUT_OBSERVE_AUTHORIZATION => {
                Ok(InputRoute::ObserveAuthorization)
            }
            short_header::INPUT_VERIFY_AUTHORIZATION => {
                Ok(InputRoute::VerifyAuthorization)
            }
            short_header::INPUT_ROUTE_SIGNATURE_REQUEST => {
                Ok(InputRoute::RouteSignatureRequest)
            }
            short_header::INPUT_SUBMIT_SIGNATURE => Ok(InputRoute::SubmitSignature),
            short_header::INPUT_REJECT_AUTHORIZATION => {
                Ok(InputRoute::RejectAuthorization)
            }
            short_header::INPUT_SUBSCRIBE_IDENTITY_UPDATES => {
                Ok(InputRoute::SubscribeIdentityUpdates)
            }
            short_header::INPUT_IDENTITY_SUBSCRIPTION_RETRACTION => {
                Ok(InputRoute::IdentitySubscriptionRetraction)
            }
            short_header::INPUT_AUTHORIZATION_OBSERVATION_RETRACTION => {
                Ok(InputRoute::AuthorizationObservationRetraction)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SignReceipt(_) => OutputRoute::SignReceipt,
            Self::VerificationResult(_) => OutputRoute::VerificationResult,
            Self::IdentityReceipt(_) => OutputRoute::IdentityReceipt,
            Self::IdentitySnapshot(_) => OutputRoute::IdentitySnapshot,
            Self::AttestationReceipt(_) => OutputRoute::AttestationReceipt,
            Self::AuthorizationPending(_) => OutputRoute::AuthorizationPending,
            Self::AuthorizationGranted(_) => OutputRoute::AuthorizationGranted,
            Self::AuthorizationDenied(_) => OutputRoute::AuthorizationDenied,
            Self::AuthorizationExpired(_) => OutputRoute::AuthorizationExpired,
            Self::AuthorizationUnavailable(_) => OutputRoute::AuthorizationUnavailable,
            Self::AuthorizationObservationSnapshot(_) => {
                OutputRoute::AuthorizationObservationSnapshot
            }
            Self::SignatureRouteReceipt(_) => OutputRoute::SignatureRouteReceipt,
            Self::SignatureSubmissionReceipt(_) => {
                OutputRoute::SignatureSubmissionReceipt
            }
            Self::AuthorizationObservationRetracted(_) => {
                OutputRoute::AuthorizationObservationRetracted
            }
            Self::SubscriptionRetracted(_) => OutputRoute::SubscriptionRetracted,
            Self::Rejection(_) => OutputRoute::Rejection,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::SignReceipt(_) => short_header::OUTPUT_SIGN_RECEIPT,
            Self::VerificationResult(_) => short_header::OUTPUT_VERIFICATION_RESULT,
            Self::IdentityReceipt(_) => short_header::OUTPUT_IDENTITY_RECEIPT,
            Self::IdentitySnapshot(_) => short_header::OUTPUT_IDENTITY_SNAPSHOT,
            Self::AttestationReceipt(_) => short_header::OUTPUT_ATTESTATION_RECEIPT,
            Self::AuthorizationPending(_) => short_header::OUTPUT_AUTHORIZATION_PENDING,
            Self::AuthorizationGranted(_) => short_header::OUTPUT_AUTHORIZATION_GRANTED,
            Self::AuthorizationDenied(_) => short_header::OUTPUT_AUTHORIZATION_DENIED,
            Self::AuthorizationExpired(_) => short_header::OUTPUT_AUTHORIZATION_EXPIRED,
            Self::AuthorizationUnavailable(_) => {
                short_header::OUTPUT_AUTHORIZATION_UNAVAILABLE
            }
            Self::AuthorizationObservationSnapshot(_) => {
                short_header::OUTPUT_AUTHORIZATION_OBSERVATION_SNAPSHOT
            }
            Self::SignatureRouteReceipt(_) => {
                short_header::OUTPUT_SIGNATURE_ROUTE_RECEIPT
            }
            Self::SignatureSubmissionReceipt(_) => {
                short_header::OUTPUT_SIGNATURE_SUBMISSION_RECEIPT
            }
            Self::AuthorizationObservationRetracted(_) => {
                short_header::OUTPUT_AUTHORIZATION_OBSERVATION_RETRACTED
            }
            Self::SubscriptionRetracted(_) => short_header::OUTPUT_SUBSCRIPTION_RETRACTED,
            Self::Rejection(_) => short_header::OUTPUT_REJECTION,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SIGN_RECEIPT => Ok(OutputRoute::SignReceipt),
            short_header::OUTPUT_VERIFICATION_RESULT => {
                Ok(OutputRoute::VerificationResult)
            }
            short_header::OUTPUT_IDENTITY_RECEIPT => Ok(OutputRoute::IdentityReceipt),
            short_header::OUTPUT_IDENTITY_SNAPSHOT => Ok(OutputRoute::IdentitySnapshot),
            short_header::OUTPUT_ATTESTATION_RECEIPT => {
                Ok(OutputRoute::AttestationReceipt)
            }
            short_header::OUTPUT_AUTHORIZATION_PENDING => {
                Ok(OutputRoute::AuthorizationPending)
            }
            short_header::OUTPUT_AUTHORIZATION_GRANTED => {
                Ok(OutputRoute::AuthorizationGranted)
            }
            short_header::OUTPUT_AUTHORIZATION_DENIED => {
                Ok(OutputRoute::AuthorizationDenied)
            }
            short_header::OUTPUT_AUTHORIZATION_EXPIRED => {
                Ok(OutputRoute::AuthorizationExpired)
            }
            short_header::OUTPUT_AUTHORIZATION_UNAVAILABLE => {
                Ok(OutputRoute::AuthorizationUnavailable)
            }
            short_header::OUTPUT_AUTHORIZATION_OBSERVATION_SNAPSHOT => {
                Ok(OutputRoute::AuthorizationObservationSnapshot)
            }
            short_header::OUTPUT_SIGNATURE_ROUTE_RECEIPT => {
                Ok(OutputRoute::SignatureRouteReceipt)
            }
            short_header::OUTPUT_SIGNATURE_SUBMISSION_RECEIPT => {
                Ok(OutputRoute::SignatureSubmissionReceipt)
            }
            short_header::OUTPUT_AUTHORIZATION_OBSERVATION_RETRACTED => {
                Ok(OutputRoute::AuthorizationObservationRetracted)
            }
            short_header::OUTPUT_SUBSCRIPTION_RETRACTED => {
                Ok(OutputRoute::SubscriptionRetracted)
            }
            short_header::OUTPUT_REJECTION => Ok(OutputRoute::Rejection),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Sign",
        "VerifyAttestation",
        "RegisterIdentity",
        "RevokeIdentity",
        "LookupIdentity",
        "AttestArchive",
        "AttestChannelGrant",
        "AttestAuthorization",
        "AuthorizeSignalCall",
        "ObserveAuthorization",
        "VerifyAuthorization",
        "RouteSignatureRequest",
        "SubmitSignature",
        "RejectAuthorization",
        "SubscribeIdentityUpdates",
        "IdentitySubscriptionRetraction",
        "AuthorizationObservationRetraction",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
